In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [17]:
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=d2l.synthetic_data(true_w,true_b,1000)

# Reading the Dataset

In [3]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [4]:
batch_size=10
data_iter = load_array((features,labels),batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-0.3637,  0.5179],
         [-0.0642,  1.5179],
         [ 1.0777, -1.2288],
         [ 1.3096, -0.3549],
         [-0.9095, -1.1763],
         [-1.5046,  0.6857],
         [-2.5740, -0.5766],
         [ 0.0190,  1.5605],
         [ 0.1720,  1.7410],
         [-0.1935, -0.3163]]),
 tensor([[ 1.6988],
         [-1.0975],
         [10.5161],
         [ 8.0296],
         [ 6.3678],
         [-1.1298],
         [ 1.0073],
         [-1.0783],
         [-1.3665],
         [ 4.8767]])]

# Defining the Model

In [19]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

# Initializing Model Parameters

In [20]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

# Defining the Loss Function

In [21]:
loss = nn.MSELoss()

 # Defining the Optimization Algorithm

In [22]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

# Training

In [23]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch+1},loss{l:f}')

epoch 1,loss0.000237
epoch 2,loss0.000092
epoch 3,loss0.000092


In [ ]:
w = net[0].weight.data
b = net[0].bias.data
print(true_w-w.reshape(true_w.shape))
print(true_b-b)

tensor([ 6.5053e-04, -1.1921e-05])
tensor([0.0005])
