In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=d2l.synthetic_data(true_w,true_b,1000)

# Reading the Dataset

In [3]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [4]:
batch_size=10
data_iter = load_array((features,labels),batch_size)

In [5]:
next(iter(data_iter))

[tensor([[ 0.9420,  1.4244],
         [-0.5195, -0.7536],
         [-0.6758,  0.2709],
         [-0.6936,  1.6467],
         [ 2.7517,  0.7307],
         [ 1.3737, -1.6293],
         [ 0.4687, -1.6939],
         [ 0.3310,  0.9792],
         [ 1.9060, -1.5730],
         [-1.8752,  0.3668]]),
 tensor([[ 1.2480],
         [ 5.6973],
         [ 1.9328],
         [-2.7932],
         [ 7.2109],
         [12.4926],
         [10.9093],
         [ 1.5472],
         [13.3712],
         [-0.7995]])]

# Defining the Model

In [6]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

# Initializing Model Parameters

In [7]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

# Defining the Loss Function

In [8]:
loss = nn.MSELoss()

 # Defining the Optimization Algorithm

In [9]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

# Training

In [10]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch+1},loss{l:f}')

epoch 1,loss0.000291
epoch 2,loss0.000104
epoch 3,loss0.000105


In [11]:
w = net[0].weight.data
b = net[0].bias.data
print(true_w-w.reshape(true_w.shape))
print(true_b-b)

tensor([0.0009, 0.0004])
tensor([0.0007])


In [14]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
target.shape,input.shape

(torch.Size([3]), torch.Size([3, 5]))